source 'https://rubygems.org'

gem 'spree', github: 'spree/spree', branch: 'master'
# Provides basic authentication functionality for testing parts of your engine
gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: 'master'
gem 'rails-controller-testing'

# Subroutine Ops
gem 'subroutine', '~> 0.5.3'

# Bulk import
gem 'activerecord-import'

gemspec
